# Generated by Django 2.0 on 2018-01-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('famale', '女'), ('male', '男')], default='男', max_length=32),
        ),
    ]
